// V2.2 Phase 3 — personal feuille (passive capture + batch curation).
//
// Storage:
//   <TRAINING_DATA_DIR>/<userId>/feuille-personnelle.md   per-user, auto-written
//   <TRAINING_DATA_DIR>/feuille-commune.md                shared, manually curated by Aaron
//
// Capture model: Claude emits `CAPTURE_RULE: <rule>` lines in its response.
// server.js extracts those lines and calls appendProposedRule() for each;
// the original lines are stripped from the response sent to the frontend.
// Rules land with [PROPOSED] status. Aaron later flips them to [VALIDATED]
// (or deletes them) by editing the file directly.
//
// Both feuilles are read fresh on every call (no caching) so manual edits
// to the .md files take effect on the next conversation turn — keeps the
// feedback loop tight without needing a server restart.
//
// Path resolution mirrors annotationStorage.dataDir(): read TRAINING_DATA_DIR
// each call so tests can sandbox under os.tmpdir().

const fs   = require('fs');
const path = require('path');

const PERSONAL_FILENAME = 'feuille-personnelle.md';
const COMMON_FILENAME   = 'feuille-commune.md';

function dataDir() {
  return process.env.TRAINING_DATA_DIR
    || path.join(__dirname, '..', '..', 'data', 'training');
}

function safeUserSeg(userId) {
  return String(userId).replace(/[\\/]/g, '_');
}

function getPersonalFeuillePath(userId) {
  return path.join(dataDir(), safeUserSeg(userId), PERSONAL_FILENAME);
}

function getCommonFeuillePath() {
  return path.join(dataDir(), COMMON_FILENAME);
}

// Strip leading status markers the model occasionally types ("CAPTURE_RULE:
// [PROPOSED] foo" → "foo"), trim, and collapse internal newlines so each
// rule lands on a single line.
function sanitizeRuleText(raw) {
  if (typeof raw !== 'string') return '';
  let s = raw.trim();
  s = s.replace(/^\[(?:PROPOSED|VALIDATED)\]\s*/i, '');
  s = s.replace(/\s*\n\s*/g, ' ');
  s = s.replace(/\s{2,}/g, ' ');
  return s.trim();
}

function buildHeader(userName, userId) {
  const who = userName || userId || '(unknown)';
  return `# Feuille personnelle — ${who} (${userId})

> Auto-generated by Claude during conversations. Lines marked [PROPOSED] are hypotheses, [VALIDATED] are confirmed by Aaron. Edit manually to validate, edit, or remove.

---

## Règles

`;
}

function loadPersonalFeuille(userId) {
  if (!userId) return '';
  const p = getPersonalFeuillePath(userId);
  if (!fs.existsSync(p)) return '';
  try { return fs.readFileSync(p, 'utf8'); }
  catch { return ''; }
}

function loadCommonFeuille() {
  const p = getCommonFeuillePath();
  if (!fs.existsSync(p)) return '';
  try { return fs.readFileSync(p, 'utf8'); }
  catch { return ''; }
}

// Append a proposed rule to the user's personal feuille. Lazy-creates the
// file with a header on first write. Best-effort: throws on filesystem
// errors so the caller can log, but never on empty-rule input (silent skip).
function appendProposedRule(userId, ruleText, scenarioId, userName) {
  if (!userId) throw new Error('[personalFeuille] appendProposedRule: userId required');
  const clean = sanitizeRuleText(ruleText);
  if (!clean) return; // empty after sanitization → silent skip

  const p = getPersonalFeuillePath(userId);
  const dir = path.dirname(p);
  fs.mkdirSync(dir, { recursive: true });

  let prefix = '';
  if (!fs.existsSync(p)) prefix = buildHeader(userName, userId);

  const originPart = scenarioId ? ` (origin: ${scenarioId})` : '';
  const line = `[PROPOSED] ${clean}${originPart}\n`;
  fs.appendFileSync(p, prefix + line);
}

// Parse a feuille file content into structured entries. Tolerant by design:
// skips headers, blockquote lines, blank lines, and any line that doesn't
// match the [STATUS] <rule> pattern. Used for diagnostics + future tooling.
function parseFeuilleEntries(content) {
  if (!content || typeof content !== 'string') return [];
  const out = [];
  // ^[STATUS] rule (origin: scenarioId)?$
  const re = /^\[(PROPOSED|VALIDATED)\]\s+(.+?)(?:\s+\(origin:\s+([^)]+)\))?\s*$/;
  for (const raw of content.split('\n')) {
    const m = re.exec(raw);
    if (!m) continue;
    out.push({
      status: m[1],
      rule:   m[2].trim(),
      origin: m[3] ? m[3].trim() : null,
    });
  }
  return out;
}

// Pull every CAPTURE_RULE line out of a Claude message and return the
// extracted rules plus a cleaned message with those lines removed.
// Multiline-anchored so we only catch lines that start with the marker
// — anything else (including the marker mid-sentence) is preserved.
//
// Returns { rules: string[], cleanText: string }. `rules` are sanitized
// (status markers stripped, single-line) so the caller can pass them
// directly to appendProposedRule.
function extractCaptureRules(rawText) {
  if (typeof rawText !== 'string' || !rawText) {
    return { rules: [], cleanText: rawText || '' };
  }
  const linePattern = /^CAPTURE_RULE:\s*(.+?)\s*$/gm;
  const rules = [];
  let m;
  while ((m = linePattern.exec(rawText)) !== null) {
    const clean = sanitizeRuleText(m[1]);
    if (clean) rules.push(clean);
  }
  // Strip the lines from the text (and consume the trailing newline so we
  // don't leave a blank gap), then collapse runs of 3+ blank lines.
  const cleanText = rawText
    .replace(/^CAPTURE_RULE:.*$\r?\n?/gm, '')
    .replace(/\n{3,}/g, '\n\n')
    .trim();
  return { rules, cleanText };
}

module.exports = {
  loadPersonalFeuille,
  loadCommonFeuille,
  appendProposedRule,
  parseFeuilleEntries,
  sanitizeRuleText,
  extractCaptureRules,
  getPersonalFeuillePath,
  getCommonFeuillePath,
};
