// Unit tests for personalFeuille — the V2.2 Phase 3 capture/storage module.
// Uses a scratch directory via TRAINING_DATA_DIR so no real annotation
// state is touched.

import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { createRequire } from 'module';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const SCRATCH_DIR = path.join(__dirname, 'tmp-feuille-data');
process.env.TRAINING_DATA_DIR = SCRATCH_DIR;

const require = createRequire(import.meta.url);
const personalFeuille = require('../personalFeuille.js');

const USER_ID   = 'test-user-feuille';
const USER_NAME = 'Tester';

describe('personalFeuille', () => {
  beforeEach(() => {
    if (fs.existsSync(SCRATCH_DIR)) fs.rmSync(SCRATCH_DIR, { recursive: true, force: true });
  });
  afterEach(() => {
    if (fs.existsSync(SCRATCH_DIR)) fs.rmSync(SCRATCH_DIR, { recursive: true, force: true });
  });

  describe('appendProposedRule', () => {
    it('creates the file with a header on first call', () => {
      personalFeuille.appendProposedRule(USER_ID, 'First rule', 'scenario-A', USER_NAME);
      const content = fs.readFileSync(personalFeuille.getPersonalFeuillePath(USER_ID), 'utf8');
      expect(content).toMatch(/^# Feuille personnelle — Tester \(test-user-feuille\)/);
      expect(content).toMatch(/Auto-generated by Claude/);
      expect(content).toContain('[PROPOSED] First rule (origin: scenario-A)');
    });

    it('does not duplicate the header on second call', () => {
      personalFeuille.appendProposedRule(USER_ID, 'First rule', 'scenario-A', USER_NAME);
      personalFeuille.appendProposedRule(USER_ID, 'Second rule', 'scenario-B', USER_NAME);
      const content = fs.readFileSync(personalFeuille.getPersonalFeuillePath(USER_ID), 'utf8');
      const headerCount = (content.match(/# Feuille personnelle/g) || []).length;
      expect(headerCount).toBe(1);
    });

    it('accumulates multiple rules in order', () => {
      personalFeuille.appendProposedRule(USER_ID, 'rule one',   'sA', USER_NAME);
      personalFeuille.appendProposedRule(USER_ID, 'rule two',   'sB', USER_NAME);
      personalFeuille.appendProposedRule(USER_ID, 'rule three', 'sC', USER_NAME);
      const entries = personalFeuille.parseFeuilleEntries(
        personalFeuille.loadPersonalFeuille(USER_ID),
      );
      expect(entries.map(e => e.rule)).toEqual(['rule one', 'rule two', 'rule three']);
    });

    it('strips leading [PROPOSED] from input rule text (sanitization)', () => {
      personalFeuille.appendProposedRule(USER_ID, '[PROPOSED] sneaky prefix', 'sX', USER_NAME);
      const entries = personalFeuille.parseFeuilleEntries(
        personalFeuille.loadPersonalFeuille(USER_ID),
      );
      expect(entries).toHaveLength(1);
      expect(entries[0].status).toBe('PROPOSED');
      expect(entries[0].rule).toBe('sneaky prefix');
    });

    it('strips leading [VALIDATED] from input rule text (sanitization)', () => {
      personalFeuille.appendProposedRule(USER_ID, '[VALIDATED] also sneaky', 'sX', USER_NAME);
      const entries = personalFeuille.parseFeuilleEntries(
        personalFeuille.loadPersonalFeuille(USER_ID),
      );
      // Even though the model typed [VALIDATED], the persisted status is
      // always [PROPOSED] — only Aaron flips entries to validated by hand.
      expect(entries[0].status).toBe('PROPOSED');
      expect(entries[0].rule).toBe('also sneaky');
    });

    it('replaces internal newlines in rule text with spaces (single-line guarantee)', () => {
      personalFeuille.appendProposedRule(USER_ID, 'line one\nline two\n  line three', 'sX', USER_NAME);
      const content = personalFeuille.loadPersonalFeuille(USER_ID);
      const lines = content.split('\n').filter(l => l.startsWith('[PROPOSED]'));
      expect(lines).toHaveLength(1);
      expect(lines[0]).toBe('[PROPOSED] line one line two line three (origin: sX)');
    });

    it('silently skips empty / whitespace-only rule text', () => {
      personalFeuille.appendProposedRule(USER_ID, '   ', 'sX', USER_NAME);
      personalFeuille.appendProposedRule(USER_ID, '',     'sX', USER_NAME);
      // No file should have been created
      expect(fs.existsSync(personalFeuille.getPersonalFeuillePath(USER_ID))).toBe(false);
    });

    it('throws when userId is missing', () => {
      expect(() => personalFeuille.appendProposedRule(null, 'rule', 'sA', USER_NAME)).toThrow(/userId/);
    });

    it('omits the (origin: ...) suffix when scenarioId is falsy', () => {
      personalFeuille.appendProposedRule(USER_ID, 'no-origin rule', null, USER_NAME);
      const entries = personalFeuille.parseFeuilleEntries(
        personalFeuille.loadPersonalFeuille(USER_ID),
      );
      expect(entries[0].rule).toBe('no-origin rule');
      expect(entries[0].origin).toBeNull();
    });
  });

  describe('loadPersonalFeuille', () => {
    it('returns empty string for non-existent user', () => {
      expect(personalFeuille.loadPersonalFeuille('nobody')).toBe('');
    });

    it('returns empty string when userId is falsy', () => {
      expect(personalFeuille.loadPersonalFeuille(null)).toBe('');
      expect(personalFeuille.loadPersonalFeuille(undefined)).toBe('');
      expect(personalFeuille.loadPersonalFeuille('')).toBe('');
    });

    it('returns content for existing file', () => {
      personalFeuille.appendProposedRule(USER_ID, 'r1', 'sA', USER_NAME);
      const content = personalFeuille.loadPersonalFeuille(USER_ID);
      expect(content).toContain('[PROPOSED] r1');
      expect(content).toMatch(/^# Feuille personnelle/);
    });
  });

  describe('loadCommonFeuille', () => {
    it('returns empty string when the file is missing', () => {
      expect(personalFeuille.loadCommonFeuille()).toBe('');
    });

    it('returns content when the file exists (manually placed by Aaron)', () => {
      const p = personalFeuille.getCommonFeuillePath();
      fs.mkdirSync(path.dirname(p), { recursive: true });
      fs.writeFileSync(p, '# Commune\n[VALIDATED] rule\n');
      expect(personalFeuille.loadCommonFeuille()).toContain('[VALIDATED] rule');
    });
  });

  describe('parseFeuilleEntries', () => {
    it('extracts [PROPOSED] entries with origin', () => {
      const out = personalFeuille.parseFeuilleEntries('[PROPOSED] foo (origin: scenario-1)');
      expect(out).toEqual([{ status: 'PROPOSED', rule: 'foo', origin: 'scenario-1' }]);
    });

    it('extracts [VALIDATED] entries without origin', () => {
      const out = personalFeuille.parseFeuilleEntries('[VALIDATED] bar');
      expect(out).toEqual([{ status: 'VALIDATED', rule: 'bar', origin: null }]);
    });

    it('ignores headers, blockquotes, blank lines, and malformed entries', () => {
      const content = `# Feuille personnelle — Tester (uid)

> Auto-generated by Claude

---

## Règles

[PROPOSED] real rule (origin: sA)
[validated] wrong-case status — should be skipped
[PROPOSED]missing space — should be skipped
random freeform commentary
[VALIDATED] another real rule
`;
      const out = personalFeuille.parseFeuilleEntries(content);
      expect(out).toEqual([
        { status: 'PROPOSED',  rule: 'real rule',         origin: 'sA' },
        { status: 'VALIDATED', rule: 'another real rule', origin: null },
      ]);
    });

    it('returns [] for empty / null input', () => {
      expect(personalFeuille.parseFeuilleEntries('')).toEqual([]);
      expect(personalFeuille.parseFeuilleEntries(null)).toEqual([]);
      expect(personalFeuille.parseFeuilleEntries(undefined)).toEqual([]);
    });
  });

  describe('sanitizeRuleText', () => {
    it('strips leading status markers, trims, collapses whitespace', () => {
      expect(personalFeuille.sanitizeRuleText('[PROPOSED]   foo   ')).toBe('foo');
      expect(personalFeuille.sanitizeRuleText('[VALIDATED] bar  baz')).toBe('bar baz');
      expect(personalFeuille.sanitizeRuleText('  plain  rule  ')).toBe('plain rule');
    });

    it('returns empty string for non-string input', () => {
      expect(personalFeuille.sanitizeRuleText(null)).toBe('');
      expect(personalFeuille.sanitizeRuleText(123)).toBe('');
    });
  });

  describe('extractCaptureRules', () => {
    it('extracts a single CAPTURE_RULE line and strips it from the message', () => {
      const raw = `OK ton raisonnement tient.

CAPTURE_RULE: pièce 4ème + ouverture 80 partenaire → capot envisageable

On note ça ?`;
      const { rules, cleanText } = personalFeuille.extractCaptureRules(raw);
      expect(rules).toEqual(['pièce 4ème + ouverture 80 partenaire → capot envisageable']);
      expect(cleanText).not.toContain('CAPTURE_RULE');
      expect(cleanText).toContain('On note ça ?');
    });

    it('extracts multiple CAPTURE_RULE lines', () => {
      const raw = `Reformulation :
CAPTURE_RULE: rule one
CAPTURE_RULE: rule two
Question suivante ?`;
      const { rules, cleanText } = personalFeuille.extractCaptureRules(raw);
      expect(rules).toEqual(['rule one', 'rule two']);
      expect(cleanText).not.toContain('CAPTURE_RULE');
    });

    it('returns empty rules + original text when no CAPTURE_RULE present', () => {
      const raw = 'Plain question without any capture.';
      const { rules, cleanText } = personalFeuille.extractCaptureRules(raw);
      expect(rules).toEqual([]);
      expect(cleanText).toBe(raw);
    });

    it('strips status markers the model may have typed inside the line', () => {
      const raw = 'CAPTURE_RULE: [PROPOSED] sneaky';
      const { rules } = personalFeuille.extractCaptureRules(raw);
      expect(rules).toEqual(['sneaky']);
    });

    it('preserves CAPTURE_RULE mentions that are NOT line-anchored', () => {
      // A discussion that mentions the marker mid-sentence should not
      // be eaten — only line-start captures are extracted.
      const raw = 'On utilise le marqueur CAPTURE_RULE: pour signaler.';
      const { rules, cleanText } = personalFeuille.extractCaptureRules(raw);
      expect(rules).toEqual([]);
      expect(cleanText).toBe(raw);
    });

    it('handles null/empty input gracefully', () => {
      expect(personalFeuille.extractCaptureRules('')).toEqual({ rules: [], cleanText: '' });
      expect(personalFeuille.extractCaptureRules(null)).toEqual({ rules: [], cleanText: '' });
    });
  });

  // Lock the round-trip composition the conversation endpoints use:
  //   raw model output  →  extractCaptureRules
  //                      →  appendProposedRule for each rule
  //                      →  cleanText goes to FE + persisted message history
  // If the server.js wiring drifts (e.g., persists raw text instead of
  // cleanText, or skips the append), the file/text expectations here flag it.
  describe('round-trip — endpoint composition', () => {
    it('captures rules to disk AND strips them from the response text', () => {
      const claudeRaw = `OK ton raisonnement tient.

CAPTURE_RULE: pièce 4ème + ouverture 80 partenaire → capot envisageable
CAPTURE_RULE: 21 promis par 80 couvre 1 perdante côté répondant

Question suivante : tu joues quoi en premier ?`;

      const { rules, cleanText } = personalFeuille.extractCaptureRules(claudeRaw);
      for (const r of rules) {
        personalFeuille.appendProposedRule(USER_ID, r, 'scenario-roundtrip', USER_NAME);
      }

      // (a) Both rules persisted as PROPOSED with the right origin
      const entries = personalFeuille.parseFeuilleEntries(
        personalFeuille.loadPersonalFeuille(USER_ID),
      );
      expect(entries).toHaveLength(2);
      expect(entries[0]).toEqual({
        status: 'PROPOSED',
        rule:   'pièce 4ème + ouverture 80 partenaire → capot envisageable',
        origin: 'scenario-roundtrip',
      });
      expect(entries[1].rule).toBe('21 promis par 80 couvre 1 perdante côté répondant');

      // (b) cleanText has no CAPTURE_RULE residue and preserves real content
      expect(cleanText).not.toMatch(/CAPTURE_RULE/);
      expect(cleanText).toContain('OK ton raisonnement tient.');
      expect(cleanText).toContain('Question suivante : tu joues quoi en premier ?');
    });
  });
});
